Error: Deployment ver.1.1.0 (#17)
* REVERT: ver.0.0.1

* 🔀: Migration from CSR to SSR (#8)

* feat: installed express package for ssr migration

* feat: setup ssr enviroment

* ✨: 파일 정리 및 환경 셋팅

* 🐛: Error pointer

- Read reference vite [guide](https://vite.dev/guide/ssr)

* 🔥: 불필요한 코드 제거

* ✨: installed react-ts with vite by yarn

* ✨: installed cross env

* ✨: created ssr sever.js and client/server entry

* ✨: need to check if SSR is enabled

* ✨: ssr test & edited server.js, index.html

* config: switch packageMananger version and chekc to build and rendering

* config: exchanged swc build package and installed the necessary packages

* config: apply to react-router-dom and transfer CSR to SSR

* remove: clear legacy code

* remove: clear legacy code

* config: apply CSR to SSR and complete the test

* 🔀: Inspect react-router-dom on SSR (#10)

* feat: installed express package for ssr migration

* feat: setup ssr enviroment

* ✨: 파일 정리 및 환경 셋팅

* 🐛: Error pointer

- Read reference vite [guide](https://vite.dev/guide/ssr)

* 🔥: 불필요한 코드 제거

* ✨: installed react-ts with vite by yarn

* ✨: installed cross env

* ✨: created ssr sever.js and client/server entry

* ✨: need to check if SSR is enabled

* ✨: ssr test & edited server.js, index.html

* config: switch packageMananger version and chekc to build and rendering

* config: exchanged swc build package and installed the necessary packages

* config: apply to react-router-dom and transfer CSR to SSR

* remove: clear legacy code

* remove: clear legacy code

* config: apply CSR to SSR and complete the test

* config: installed scss and changed css to scc

* feat: implemented the main develop branch about Home.tsx and scss

* feat: Improving the environment to prevent another hydration mismatch.

* feat: created route components and improved the hydration mismatch that occurred in Test.tsx.

* feat: Set up Yarn for local execution

* Error: resolved `No routes matched location "test"` Error

- due to `Test.tsx`file, specifically in the Hydration check, the syntax disturbs the router. Now, have a question: where was the Hydration error resolved?

* config: SSR Migration is Done.

- resolved Hydration mismatch Error
- resolved `No routes matched location "test"` by react-router-dom Error

* remove: deleted unnecessary code

* Re: Inspect react-router-dom on SSR (#11)

* feat: installed express package for ssr migration

* feat: setup ssr enviroment

* ✨: 파일 정리 및 환경 셋팅

* 🐛: Error pointer

- Read reference vite [guide](https://vite.dev/guide/ssr)

* 🔥: 불필요한 코드 제거

* ✨: installed react-ts with vite by yarn

* ✨: installed cross env

* ✨: created ssr sever.js and client/server entry

* ✨: need to check if SSR is enabled

* ✨: ssr test & edited server.js, index.html

* config: switch packageMananger version and chekc to build and rendering

* config: exchanged swc build package and installed the necessary packages

* config: apply to react-router-dom and transfer CSR to SSR

* remove: clear legacy code

* remove: clear legacy code

* config: apply CSR to SSR and complete the test

* config: installed scss and changed css to scc

* feat: implemented the main develop branch about Home.tsx and scss

* feat: Improving the environment to prevent another hydration mismatch.

* feat: created route components and improved the hydration mismatch that occurred in Test.tsx.

* feat: Set up Yarn for local execution

* Error: resolved `No routes matched location "test"` Error

- due to `Test.tsx`file, specifically in the Hydration check, the syntax disturbs the router. Now, have a question: where was the Hydration error resolved?

* config: SSR Migration is Done.

- resolved Hydration mismatch Error
- resolved `No routes matched location "test"` by react-router-dom Error

* feat: resolved Hydration mismatch Error

- still error: No routes matched location "test" by compiler

* Re-error: Fixed the 'No Routes Matched Location' error and resolved the issue of integrating all pages for rendering. (#12)

Don't know why the 'No routes matched location "/test"' error occurs.

* feat: resolved Error

* Error: resolved error

* Error: added vercel.json and reset up vercel environment